# Generated by Django 4.2.3 on 2023-08-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServersForRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Role.role')),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Role.server')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='servers',
            field=models.ManyToManyField(through='Role.ServersForRole', to='Role.server'),
        ),
    ]
